### ISSUE TITLE
i Submited same solution for Distinct Colors but got tle

### ISSUE THREAD

**Issue by anishagg17** [0x5eba/CSES-solutions#1]
https://github.com/0x5eba/CSES-solutions/blob/c18b66262f5dbef44b58d793f5185c3d0cf3a77c/TreeAlgorithms/DistinctColors/m.cpp#L1

Link to submission :

https://cses.fi/problemset/result/393326/

**Comment by 0x5eba** [comment]
I also get TLE, it was the only Tree Algorithms problem that I failed. There are also some other problems that I didn't entirely solved.
Feel free to search for a better solution and make a pull request :)
